# Generated by Django 4.1.7 on 2023-05-12 19:27

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Myip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_txt', models.CharField(max_length=15)),
                ('pubdate', models.DateField(default=datetime.date.today)),
            ],
        ),
    ]
